services:
  # Backend API service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fitness-tracker-backend
    restart: always
    volumes:
      - ./backend:/app
      - backend_data:/app/instance
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - SECRET_KEY=dev-secret-key-change-in-production
      - JWT_SECRET_KEY=dev-jwt-secret-key-change-in-production
    ports:
      - "5002:5000"

  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_URL: http://localhost
    container_name: fitness-tracker-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost

volumes:
  backend_data:
